[build]
target = "index.html"
dist = "dist"
public_url = "/"
release = false

[serve]
port = 5001
open = false
addresses = ["127.0.0.1"]

[[hooks]]
stage = "pre_build"
command = "bun"
command_arguments = ["run", "build"]
