name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*'
      - 'tests/**/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/*'
      - 'tests/**/*'

env:
  CARGO_TERM_COLOR: always
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: ENV
      run: echo "$DATABASE_URL"
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.3.0
      with:
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        file_name: .env
        fail_on_empty: false
    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
