name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*'
      - 'tests/**/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/*'
      - 'tests/**/*'

env:
  CARGO_TERM_COLOR: always
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: ./build.sh
    - name: Run tests
      run: cargo test --verbose
